baseURL: http://pebcac.org/
languageCode: en-us
title: Pebcac Thoughts
theme: PaperMod

params:
  homeInfoParams:
    Title: "Tech Journal"
    Content: "Exploring the wide world of tech"
  socialIcons:
    - name: github
      url: "https://github.com/pebcac"
    - name: twitter
      url: "https://twitter.com/"

  languages:
    en:
      languageName: English
      weight: 1
      disabled: false
      languageCode: en-US
    es:
      languageName: Spanish
      weight: 2
    pt-br:
      languageName: Portuguese
      weight: 3
      disabled: false
      languageCode: pt-br

  cover:
    linkFullImages: true

  ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true

  ShowCodeCopyButtons: true

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 40
