baseURL = "https://pebcac.org"
title = "HBS (Hugo Theme Bootstrap) v1"
theme = "PaperMod" # install via git submodule
# theme = "github.com/razonyang/hugo-theme-bootstrap" # install via hugo module
copyright = "Copyright © 2016-{year} Razon Yang. All Rights Reserved."

# Multilingual mode
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true # If you use only one language comment this option
# disableLanguages = ["fr", "zh-cn" ,"zh-tw", "ar", "ja"] # Uncomment in order to disable one or more language

# Pagination
paginate = 10
# paginatePath = "page"

# Disqus
# disqusShortname = "yourdiscussshortname"

# Google analytics
# googleAnalytics = "UA-123-45"

enableRobotsTXT = false

enableEmoji = true

enableGitInfo = true

# Add Papermod to Hugo and update it by running `hugo mod get -u`
#module:
#  imports:
#    - path: github.com/adityatelange/hugo-PaperMod

# hasCJKLanguage = true # Uncomment it if your content contains Chinese/Japanese/Korean Languages.

pygmentsUseClasses = true

timeout = "120s"

[blackfriday]
  hrefTargetBlank = true

[outputs]
  home = ["HTML", "RSS"]

[taxonomies]
  blog = "blog"
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[build]
  writeStats = true

